--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg110+2)
-- Dumped by pg_dump version 16.4 (Debian 16.4-1.pgdg110+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tiger; Type: SCHEMA; Schema: -; Owner: awm_developer
--

CREATE SCHEMA tiger;


ALTER SCHEMA tiger OWNER TO awm_developer;

--
-- Name: tiger_data; Type: SCHEMA; Schema: -; Owner: awm_developer
--

CREATE SCHEMA tiger_data;


ALTER SCHEMA tiger_data OWNER TO awm_developer;

--
-- Name: topology; Type: SCHEMA; Schema: -; Owner: awm_developer
--

CREATE SCHEMA topology;


ALTER SCHEMA topology OWNER TO awm_developer;

--
-- Name: SCHEMA topology; Type: COMMENT; Schema: -; Owner: awm_developer
--

COMMENT ON SCHEMA topology IS 'PostGIS Topology schema';


--
-- Name: fuzzystrmatch; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS fuzzystrmatch WITH SCHEMA public;


--
-- Name: EXTENSION fuzzystrmatch; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION fuzzystrmatch IS 'determine similarities and distance between strings';


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- Name: postgis_tiger_geocoder; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder WITH SCHEMA tiger;


--
-- Name: EXTENSION postgis_tiger_geocoder; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis_tiger_geocoder IS 'PostGIS tiger geocoder and reverse geocoder';


--
-- Name: postgis_topology; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA topology;


--
-- Name: EXTENSION postgis_topology; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis_topology IS 'PostGIS topology spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO awm_developer;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO awm_developer;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO awm_developer;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO awm_developer;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO awm_developer;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO awm_developer;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO awm_developer;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO awm_developer;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO awm_developer;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO awm_developer;

--
-- Name: spatial_analysis_dublinadminarea; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.spatial_analysis_dublinadminarea (
    id bigint NOT NULL,
    area_name character varying(100) NOT NULL,
    area_type character varying(50) NOT NULL,
    population integer,
    area_km2 numeric(10,2) NOT NULL,
    geom public.geometry(Polygon,4326),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.spatial_analysis_dublinadminarea OWNER TO awm_developer;

--
-- Name: spatial_analysis_dublinadminarea_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.spatial_analysis_dublinadminarea ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spatial_analysis_dublinadminarea_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spatial_analysis_dublinpoi; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.spatial_analysis_dublinpoi (
    id bigint NOT NULL,
    poi_name character varying(100) NOT NULL,
    poi_type character varying(20) NOT NULL,
    description text NOT NULL,
    visitors_per_day integer,
    rating numeric(3,2),
    geom public.geometry(Point,4326),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.spatial_analysis_dublinpoi OWNER TO awm_developer;

--
-- Name: spatial_analysis_dublinpoi_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.spatial_analysis_dublinpoi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spatial_analysis_dublinpoi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spatial_analysis_dublinroad; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.spatial_analysis_dublinroad (
    id bigint NOT NULL,
    road_name character varying(100) NOT NULL,
    road_type character varying(20) NOT NULL,
    speed_limit integer NOT NULL,
    length_meters numeric(10,2) NOT NULL,
    geom public.geometry(LineString,4326),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.spatial_analysis_dublinroad OWNER TO awm_developer;

--
-- Name: spatial_analysis_dublinroad_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.spatial_analysis_dublinroad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spatial_analysis_dublinroad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spatial_analysis_landusezone; Type: TABLE; Schema: public; Owner: awm_developer
--

CREATE TABLE public.spatial_analysis_landusezone (
    id bigint NOT NULL,
    zone_name character varying(100) NOT NULL,
    zone_type character varying(20) NOT NULL,
    zoning_code character varying(20) NOT NULL,
    permitted_uses text NOT NULL,
    geom public.geometry(Polygon,4326),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.spatial_analysis_landusezone OWNER TO awm_developer;

--
-- Name: spatial_analysis_landusezone_id_seq; Type: SEQUENCE; Schema: public; Owner: awm_developer
--

ALTER TABLE public.spatial_analysis_landusezone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spatial_analysis_landusezone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add dublin admin area	7	add_dublinadminarea
26	Can change dublin admin area	7	change_dublinadminarea
27	Can delete dublin admin area	7	delete_dublinadminarea
28	Can view dublin admin area	7	view_dublinadminarea
29	Can add Dublin POI	8	add_dublinpoi
30	Can change Dublin POI	8	change_dublinpoi
31	Can delete Dublin POI	8	delete_dublinpoi
32	Can view Dublin POI	8	view_dublinpoi
33	Can add dublin road	9	add_dublinroad
34	Can change dublin road	9	change_dublinroad
35	Can delete dublin road	9	delete_dublinroad
36	Can view dublin road	9	view_dublinroad
37	Can add Land Use Zone	10	add_landusezone
38	Can change Land Use Zone	10	change_landusezone
39	Can delete Land Use Zone	10	delete_landusezone
40	Can view Land Use Zone	10	view_landusezone
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$O0aewd4NImk2oMC19Yvoed$CRWINb73FiOEc0qFuPpBIngFQrjf4o4X6BWmDmGDjMU=	2026-09-23 21:03:01.751828+00	t	root			C23316153@mytudublin.ie	t	t	2026-09-23 21:01:49.457685+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	spatial_analysis	dublinadminarea
8	spatial_analysis	dublinpoi
9	spatial_analysis	dublinroad
10	spatial_analysis	landusezone
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	spatial_analysis	0001_initial	2026-09-23 21:01:21.323157+00
2	contenttypes	0001_initial	2026-09-23 21:01:28.623585+00
3	auth	0001_initial	2026-09-23 21:01:28.713248+00
4	admin	0001_initial	2026-09-23 21:01:28.740669+00
5	admin	0002_logentry_remove_auto_add	2026-09-23 21:01:28.750024+00
6	admin	0003_logentry_add_action_flag_choices	2026-09-23 21:01:28.759128+00
7	contenttypes	0002_remove_content_type_name	2026-09-23 21:01:28.786865+00
8	auth	0002_alter_permission_name_max_length	2026-09-23 21:01:28.798632+00
9	auth	0003_alter_user_email_max_length	2026-09-23 21:01:28.80877+00
10	auth	0004_alter_user_username_opts	2026-09-23 21:01:28.819365+00
11	auth	0005_alter_user_last_login_null	2026-09-23 21:01:28.830678+00
12	auth	0006_require_contenttypes_0002	2026-09-23 21:01:28.833144+00
13	auth	0007_alter_validators_add_error_messages	2026-09-23 21:01:28.842909+00
14	auth	0008_alter_user_username_max_length	2026-09-23 21:01:28.861069+00
15	auth	0009_alter_user_last_name_max_length	2026-09-23 21:01:28.872019+00
16	auth	0010_alter_group_name_max_length	2026-09-23 21:01:28.884997+00
17	auth	0011_update_proxy_permissions	2026-09-23 21:01:28.897212+00
18	auth	0012_alter_user_first_name_max_length	2026-09-23 21:01:28.907733+00
19	sessions	0001_initial	2026-09-23 21:01:28.926933+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
6sitv335l7s7iffvsrk5m6rqa1tsjyvo	.eJxVjLsOgkAUBf9la7PZF-vF0p5v2NwXghpIWKiM_64kFNqemTkvU3Bbh7JVXcoo5mK8Of1uhPzQaQdyx-k2W56ndRnJ7oo9aLXdLPq8Hu7fwYB1-NZI6DiyglOBBnruueU25CjaR20IAuWYRF3CBJAwnpG8yxK9UwrgzfsDFU04gw:1x9U7J:r130Umhwf5xFYREb2nqYT6PRoH4DkiD3q04hWcTSs2c	2026-10-07 21:03:01.754831+00
\.


--
-- Data for Name: spatial_analysis_dublinadminarea; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.spatial_analysis_dublinadminarea (id, area_name, area_type, population, area_km2, geom, created_at, updated_at) FROM stdin;
1	Dublin City Centre	city_center	25000	5.20	0103000020E610000001000000050000001F85EB51B81E19C07B14AE47E1AA4A40F6285C8FC2F518C07B14AE47E1AA4A40F6285C8FC2F518C01F85EB51B8AE4A401F85EB51B81E19C01F85EB51B8AE4A401F85EB51B81E19C07B14AE47E1AA4A40	2026-09-23 21:02:33.194173+00	2026-09-23 21:02:33.194211+00
2	Temple Bar District	cultural_quarter	8000	1.10	0103000020E6100000010000000500000014AE47E17A1419C096438B6CE7AB4A400AD7A3703D0A19C096438B6CE7AB4A400AD7A3703D0A19C0068195438BAC4A4014AE47E17A1419C0068195438BAC4A4014AE47E17A1419C096438B6CE7AB4A40	2026-09-23 21:02:33.305601+00	2026-09-23 21:02:33.305625+00
3	Phoenix Park Area	recreational	15000	12.50	0103000020E610000001000000050000005C8FC2F5285C19C0CDCCCCCCCCAC4A4048E17A14AE4719C0CDCCCCCCCCAC4A4048E17A14AE4719C0AE47E17A14AE4A405C8FC2F5285C19C0AE47E17A14AE4A405C8FC2F5285C19C0CDCCCCCCCCAC4A40	2026-09-23 21:02:33.397641+00	2026-09-23 21:02:33.397668+00
4	Docklands	business	18000	3.80	0103000020E61000000100000005000000EC51B81E85EB18C0EC51B81E85AB4A40D7A3703D0AD718C0EC51B81E85AB4A40D7A3703D0AD718C0CDCCCCCCCCAC4A40EC51B81E85EB18C0CDCCCCCCCCAC4A40EC51B81E85EB18C0EC51B81E85AB4A40	2026-09-23 21:02:33.480568+00	2026-09-23 21:02:33.480588+00
5	Ballsbridge	residential	22000	4.20	0103000020E61000000100000005000000E17A14AE47E118C09A99999999A94A40CDCCCCCCCCCC18C09A99999999A94A40CDCCCCCCCCCC18C07B14AE47E1AA4A40E17A14AE47E118C07B14AE47E1AA4A40E17A14AE47E118C09A99999999A94A40	2026-09-23 21:02:33.553064+00	2026-09-23 21:02:33.553085+00
\.


--
-- Data for Name: spatial_analysis_dublinpoi; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.spatial_analysis_dublinpoi (id, poi_name, poi_type, description, visitors_per_day, rating, geom, created_at, updated_at) FROM stdin;
1	Trinity College Library	education	Historic university library with the Book of Kells	2500	4.80	0101000020E61000005F984C158C0A19C0DC4603780BAC4A40	2026-09-23 21:02:33.962972+00	2026-09-23 21:02:33.962992+00
2	Dublin Castle	historic	Historic castle in the heart of Dublin	1800	4.50	0101000020E610000036CD3B4ED11119C032E6AE25E4AB4A40	2026-09-23 21:02:34.024276+00	2026-09-23 21:02:34.024305+00
3	Temple Bar Pub	entertainment	Historic pub in Temple Bar cultural quarter	3000	4.20	0101000020E61000008C4AEA04341119C087A757CA32AC4A40	2026-09-23 21:02:34.096108+00	2026-09-23 21:02:34.096134+00
4	Phoenix Park Visitor Centre	attraction	Visitor centre for Europe's largest enclosed urban park	1200	4.60	0101000020E610000019E25817B75119C05AF5B9DA8AAD4A40	2026-09-23 21:02:34.159315+00	2026-09-23 21:02:34.159338+00
5	Dublin Port	transport	Major shipping and ferry terminal	5000	4.00	0101000020E6100000E17A14AE47E118C05C8FC2F528AC4A40	2026-09-23 21:02:34.229255+00	2026-09-23 21:02:34.229274+00
6	St. Stephen's Green Shopping	commercial	Major shopping center on historic green space	15000	4.40	0101000020E6100000D578E926310819C041F163CC5DAB4A40	2026-09-23 21:02:34.2932+00	2026-09-23 21:02:34.293222+00
7	Guinness Storehouse	attraction	Museum and visitor attraction dedicated to Guinness	4000	4.70	0101000020E61000004694F6065F1819C096B20C71ACAB4A40	2026-09-23 21:02:34.36512+00	2026-09-23 21:02:34.365143+00
\.


--
-- Data for Name: spatial_analysis_dublinroad; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.spatial_analysis_dublinroad (id, road_name, road_type, speed_limit, length_meters, geom, created_at, updated_at) FROM stdin;
1	O'Connell Street	main_street	30	500.00	0102000020E6100000020000005F984C158C0A19C00612143FC6AC4A405F984C158C0A19C0764F1E166AAD4A40	2026-09-23 21:02:33.618698+00	2026-09-23 21:02:33.61872+00
2	Grafton Street	pedestrian	0	400.00	0102000020E61000000200000027C286A7570A19C02497FF907EAB4A4027C286A7570A19C095D4096822AC4A40	2026-09-23 21:02:33.691088+00	2026-09-23 21:02:33.691107+00
3	Dame Street	main_street	30	600.00	0102000020E610000002000000696FF085C91419C024B9FC87F4AB4A405F984C158C0A19C024B9FC87F4AB4A40	2026-09-23 21:02:33.754547+00	2026-09-23 21:02:33.754567+00
4	Quays Road	secondary	50	1200.00	0102000020E610000002000000744694F6061F19C05C2041F163AC4A404BEA043411F618C05C2041F163AC4A40	2026-09-23 21:02:33.826615+00	2026-09-23 21:02:33.826644+00
5	Ring Road M50	motorway	100	2000.00	0102000020E610000002000000BB270F0BB56619C0E78C28ED0DAE4A40228E75711BCD18C0431CEBE236AA4A40	2026-09-23 21:02:33.890518+00	2026-09-23 21:02:33.890549+00
\.


--
-- Data for Name: spatial_analysis_landusezone; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.spatial_analysis_landusezone (id, zone_name, zone_type, zoning_code, permitted_uses, geom, created_at, updated_at) FROM stdin;
1	City Centre Mixed Use	mixed_use	Z01	Retail, Office, Residential, Cultural, Recreation	0103000020E610000001000000050000001F85EB51B81E19C07B14AE47E1AA4A40F6285C8FC2F518C07B14AE47E1AA4A40F6285C8FC2F518C01F85EB51B8AE4A401F85EB51B81E19C01F85EB51B8AE4A401F85EB51B81E19C07B14AE47E1AA4A40	2026-09-23 21:02:34.432027+00	2026-09-23 21:02:34.432046+00
2	Docklands Commercial	commercial	Z02	Office, Retail, Business Services, Hotels	0103000020E61000000100000005000000EC51B81E85EB18C0EC51B81E85AB4A40D7A3703D0AD718C0EC51B81E85AB4A40D7A3703D0AD718C0CDCCCCCCCCAC4A40EC51B81E85EB18C0CDCCCCCCCCAC4A40EC51B81E85EB18C0EC51B81E85AB4A40	2026-09-23 21:02:34.502656+00	2026-09-23 21:02:34.50268+00
3	Residential South Dublin	residential	Z03	Residential, Local Services, Community Facilities	0103000020E61000000100000005000000E17A14AE47E118C09A99999999A94A40CDCCCCCCCCCC18C09A99999999A94A40CDCCCCCCCCCC18C07B14AE47E1AA4A40E17A14AE47E118C07B14AE47E1AA4A40E17A14AE47E118C09A99999999A94A40	2026-09-23 21:02:34.566531+00	2026-09-23 21:02:34.566554+00
4	Phoenix Park Protected	protected	Z04	Recreation, Cultural Events, Education, Conservation	0103000020E610000001000000050000005C8FC2F5285C19C0CDCCCCCCCCAC4A4048E17A14AE4719C0CDCCCCCCCCAC4A4048E17A14AE4719C0AE47E17A14AE4A405C8FC2F5285C19C0AE47E17A14AE4A405C8FC2F5285C19C0CDCCCCCCCCAC4A40	2026-09-23 21:02:34.638404+00	2026-09-23 21:02:34.638423+00
\.


--
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: awm_developer
--

COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.


--
-- Data for Name: geocode_settings; Type: TABLE DATA; Schema: tiger; Owner: awm_developer
--

COPY tiger.geocode_settings (name, setting, unit, category, short_desc) FROM stdin;
\.


--
-- Data for Name: pagc_gaz; Type: TABLE DATA; Schema: tiger; Owner: awm_developer
--

COPY tiger.pagc_gaz (id, seq, word, stdword, token, is_custom) FROM stdin;
\.


--
-- Data for Name: pagc_lex; Type: TABLE DATA; Schema: tiger; Owner: awm_developer
--

COPY tiger.pagc_lex (id, seq, word, stdword, token, is_custom) FROM stdin;
\.


--
-- Data for Name: pagc_rules; Type: TABLE DATA; Schema: tiger; Owner: awm_developer
--

COPY tiger.pagc_rules (id, rule, is_custom) FROM stdin;
\.


--
-- Data for Name: topology; Type: TABLE DATA; Schema: topology; Owner: awm_developer
--

COPY topology.topology (id, name, srid, "precision", hasz) FROM stdin;
\.


--
-- Data for Name: layer; Type: TABLE DATA; Schema: topology; Owner: awm_developer
--

COPY topology.layer (topology_id, layer_id, schema_name, table_name, feature_column, feature_type, level, child_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: spatial_analysis_dublinadminarea_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.spatial_analysis_dublinadminarea_id_seq', 5, true);


--
-- Name: spatial_analysis_dublinpoi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.spatial_analysis_dublinpoi_id_seq', 7, true);


--
-- Name: spatial_analysis_dublinroad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.spatial_analysis_dublinroad_id_seq', 5, true);


--
-- Name: spatial_analysis_landusezone_id_seq; Type: SEQUENCE SET; Schema: public; Owner: awm_developer
--

SELECT pg_catalog.setval('public.spatial_analysis_landusezone_id_seq', 4, true);


--
-- Name: topology_id_seq; Type: SEQUENCE SET; Schema: topology; Owner: awm_developer
--

SELECT pg_catalog.setval('topology.topology_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: spatial_analysis_dublinadminarea spatial_analysis_dublinadminarea_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.spatial_analysis_dublinadminarea
    ADD CONSTRAINT spatial_analysis_dublinadminarea_pkey PRIMARY KEY (id);


--
-- Name: spatial_analysis_dublinpoi spatial_analysis_dublinpoi_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.spatial_analysis_dublinpoi
    ADD CONSTRAINT spatial_analysis_dublinpoi_pkey PRIMARY KEY (id);


--
-- Name: spatial_analysis_dublinroad spatial_analysis_dublinroad_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.spatial_analysis_dublinroad
    ADD CONSTRAINT spatial_analysis_dublinroad_pkey PRIMARY KEY (id);


--
-- Name: spatial_analysis_landusezone spatial_analysis_landusezone_pkey; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.spatial_analysis_landusezone
    ADD CONSTRAINT spatial_analysis_landusezone_pkey PRIMARY KEY (id);


--
-- Name: spatial_analysis_landusezone spatial_analysis_landusezone_zoning_code_key; Type: CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.spatial_analysis_landusezone
    ADD CONSTRAINT spatial_analysis_landusezone_zoning_code_key UNIQUE (zoning_code);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: spatial_analysis_dublinadminarea_geom_3b9ccea2_id; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX spatial_analysis_dublinadminarea_geom_3b9ccea2_id ON public.spatial_analysis_dublinadminarea USING gist (geom);


--
-- Name: spatial_analysis_dublinpoi_geom_b8759e1f_id; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX spatial_analysis_dublinpoi_geom_b8759e1f_id ON public.spatial_analysis_dublinpoi USING gist (geom);


--
-- Name: spatial_analysis_dublinroad_geom_b854f308_id; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX spatial_analysis_dublinroad_geom_b854f308_id ON public.spatial_analysis_dublinroad USING gist (geom);


--
-- Name: spatial_analysis_landusezone_geom_08cda31d_id; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX spatial_analysis_landusezone_geom_08cda31d_id ON public.spatial_analysis_landusezone USING gist (geom);


--
-- Name: spatial_analysis_landusezone_zoning_code_88d2af97_like; Type: INDEX; Schema: public; Owner: awm_developer
--

CREATE INDEX spatial_analysis_landusezone_zoning_code_88d2af97_like ON public.spatial_analysis_landusezone USING btree (zoning_code varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: awm_developer
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

